inv: "auto" # инвертирование данных "auto" / True / False
point_start: 0 # начало обработки данных в метрах
point_end: 5000 # конец обработки данных в метрах
point_cut: 2500 # точка линии в метрах, на которой смотрим срез частот
freq_cut: 10800 # частота в МГц, на которой срез рефлектограммы
num_pts_norm: 20 # количество точек, по которым выполняется нормировка
transparency: 0.6 # прозрачность графика пиков, которые мы определили